version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/my-realm.import.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
    ports:
      - 28080:8080

  db:
    image: postgres:15-alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dataBASE
      POSTGRES_DB: FullStackTemplate
